### ISSUE TITLE
添加响应式设计支持 - 提升移动端用户体验

### ISSUE THREAD

**Issue by bdsunben96** [bdsunben96/helloworld#27]
## 问题描述
当前页面布局使用固定宽度的侧边栏（200px），在小屏幕设备上会导致内容区域过窄，影响移动端用户体验。

## 当前问题
- 左右侧边栏固定宽度200px，在手机等小屏幕设备上占用过多空间
- 缺少媒体查询，无法根据屏幕尺寸调整布局
- 导航菜单在小屏幕上可能显示不佳

## 建议改进
- 添加CSS媒体查询，针对不同屏幕尺寸优化布局
- 在小屏幕上隐藏或折叠侧边栏
- 考虑将导航菜单改为汉堡菜单样式
- 确保内容在各种设备上都有良好的可读性

## 示例媒体查询
```css
@media (max-width: 768px) {
  .leftbar, .rightbar {
    display: none;
  }
  .main {
    flex-direction: column;
  }
}
```

## 优先级
中 - 随着移动端访问增加，响应式设计变得越来越重要
