### ISSUE TITLE
UI-ISSUE: 缺少响应式设计的媒体查询

### ISSUE THREAD

**Issue by bdsunben96** [bdsunben96/helloworld#40]
当前页面布局没有实现响应式设计的媒体查询，这会导致在移动设备上显示不佳。虽然有设置了 viewport meta 标签，但没有相应的 CSS 媒体查询来适应不同屏幕尺寸。

**建议修改**：
添加媒体查询以适应不同的屏幕尺寸，特别是对于侧边栏的处理，在小屏幕设备上应该调整布局，例如：

```css
@media (max-width: 768px) {
    .main {
        flex-direction: column;
    }
    
    .leftbar, .rightbar {
        width: 100%;
    }
}
```
