### ISSUE TITLE
WEB-ISSUE: 缺少 CSS 变量和样式组织

### ISSUE THREAD

**Issue by bdsunben96** [bdsunben96/helloworld#42]
当前样式表中的颜色值和尺寸直接硬编码在各个选择器中，这使得样式难以维护和统一修改。

**建议修改**：
1. 使用 CSS 变量（自定义属性）来定义颜色、间距和其他重复使用的值
2. 将样式组织成更有逻辑的结构，例如按照布局、组件、主题等分类

示例：
```css
:root {
    --color-bg-primary: #f0f0f0;
    --color-bg-secondary: #e0e0e0;
    --color-bg-tertiary: #c0c0c0;
    --color-bg-footer: #d0d0d0;
    --spacing-standard: 20px;
}

.header {
    background-color: var(--color-bg-primary);
    padding: var(--spacing-standard);
    /* 其他样式 */
}
```

这样的改进可以使样式表更易于维护，并且在需要更改主题或调整设计时更加灵活。
